gems:
  - jekyll-seo-tag

url: https://ariadnaballestar.com
baseurl: ""
enforce_ssl: ariadnaballestar.com

title: Ariadna Ballestar Fotografía

description: Fotógrafa profesional en Barcelona y Fraga. Fotografía de pareja, embarazo, familia, grupos, para regalar y más... Presupuestos adaptados a tus necesidades.

author: Ariadna Ballestar

logo: assets/logos/logo-negro.png

social: 
  name: Ariadna Ballestar Fotografía
  links:
    - https://www.instagram.com/ariadna_ballestar/
    - https://www.facebook.com/ari.ballestar

facebook:
  publisher: https://www.facebook.com/ari.ballestar

email: info@ariadnaballestar.com


lang: es_ES

markdown: kramdown

webmaster_verifications:
  google: wCAUJatFeERGPOT1QzbB82H1bwA1cZUN31DXSsm4vPE